services:
    nginx:
        image: nginx:1.25.3-alpine
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        networks:
            - app-network
    php:
        build:
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        extra_hosts:
            - host.docker.internal:host-gateway
    front:
        image: node:24
        working_dir: /var/www/html
        build:
            context: .
            dockerfile: docker/front/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - '3000:3000'
        depends_on:
            - php
        networks:
            - app-network
        tty: true
    db:
        image: postgres:17.5
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:  # Docker автоматически создаст том с этим именем
